variables:
  DEPLOYMENT_NAME: landing-service
  GITLAB_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  # Google Cloud configuration
  GOOGLE_PROJECT_ID: valued-etching-440310-b3
  REGION: asia-east1 # adjust to your region
  CLUSTER_NAME: developmect-cluster

stages:
  - build
  - deploy-dev
  - deploy-staging
  - deploy-prod

.build_template: &build_definition
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "Promoting staging image to release version: $CI_COMMIT_TAG"
        # Find the corresponding staging tag
        docker pull ${CI_REGISTRY_IMAGE}:staging
        docker tag ${CI_REGISTRY_IMAGE}:staging ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
        docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
      elif [[ "$CI_COMMIT_TAG" =~ ^staging ]]; then
        echo "Building staging version: $CI_COMMIT_TAG"
        docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .
        docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
      else
        echo "Building branch version: $CI_COMMIT_BRANCH"
        docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH} .
        docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}
      fi

build:
  <<: *build_definition
  variables:
    IMAGE_TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG =~ /^staging/
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/

deploy-dev:
  stage: deploy-dev
  tags:
    - kube
  script:
    - PATH=/root/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    - kubectl config use-context gke_valued-etching-440310-b3_asia-east1_development-cluster
    - kubectl rollout restart deployment "${DEPLOYMENT_NAME}"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy-staging:
  stage: deploy-staging
  tags:
    - kube
  script:
    - PATH=/root/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    - kubectl config use-context gke_valued-etching-440310-b3_asia-east1_staging-cluster
    - kubectl rollout restart deployment "${DEPLOYMENT_NAME}"
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG =~ /^staging/

deploy-prod:
  stage: deploy-prod
  tags:
    - kube
  script:
    - PATH=/root/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    - kubectl config use-context gke_valued-etching-440310-b3_asia-east1_production-cluster    
    - kubectl set image deployment/"${DEPLOYMENT_NAME}" "${DEPLOYMENT_NAME}=${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - kubectl rollout status deployment/"${DEPLOYMENT_NAME}"
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/